export { OnlineNeedsDecay } from './needs.js';
export type { NeedsConfig, NeedsTickResult } from './needs.js';
export { applyInteraction } from './interaction-effects.js';
export type { InteractionEffect } from './interaction-effects.js';
export { CooldownManager, DEFAULT_COOLDOWNS } from './cooldowns.js';
export type { CooldownConfig } from './cooldowns.js';
export { ThoughtCycle } from './thought-cycle.js';
export type { Thought, AutonomousAction, ThoughtCycleConfig } from './thought-cycle.js';
export { resolveEmotion } from './resolver.js';
export { getHungerPersonality, applyHungerPersonality } from './hunger-personality.js';
export type { HungerModifiers } from './hunger-personality.js';
export { checkIgnore, createIgnoreState, resetIgnoreState } from './ignore-detection.js';
export type { IgnoreState, IgnoreAction, IgnoreResult } from './ignore-detection.js';
export { checkDiscomfort, createDiscomfortState } from './discomfort.js';
export type { DiscomfortConfig, DiscomfortState } from './discomfort.js';
export { evaluateOverride, applyOverride, hasOverride } from './expression-override.js';
export type { ExpressionOverride, OverrideState } from './expression-override.js';
